name: IPLog
version: '1.0-SNAPSHOT'
main: ljsure.cn.IPLog
api-version: '1.20'
load: STARTUP
authors: [ ljsure ]
commands:
  iplog:
    description: 查询玩家的IP信息
    usage: /<command> <玩家名>
    permission: iplog.query
permissions:
  iplog.query:
    description: 允许查询玩家IP信息
    default: op